ALTER TABLE SII_ACTA_VISITA_SIVO ADD AVI_ESTADO_NOTIFICACION VARCHAR2(20) DEFAULT 'PENDIENTE';
ALTER TABLE SII_ACTA_VISITA_SIVO ADD AVI_INTENTOS_NOTIFICACION NUMBER DEFAULT 0;
ALTER TABLE SII_ACTA_VISITA_SIVO ADD AVI_ULTIMO_ERROR VARCHAR2(4000);
